# Generated by Django 5.1.6 on 2025-02-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdocument',
            old_name='document_file',
            new_name='addhar_card',
        ),
        migrations.RemoveField(
            model_name='userdocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='userdocument',
            name='pan_card',
            field=models.FileField(null=True, upload_to='user_documents/'),
        ),
    ]
